// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByFydEFIyUa1kHWNUPr8HUyfjqn-_pbZ4',
    appId: '1:473743969289:web:471cdff5a32cee5aae3cd8',
    messagingSenderId: '473743969289',
    projectId: 'bigshow-32ef4',
    authDomain: 'bigshow-32ef4.firebaseapp.com',
    databaseURL: 'https://bigshow-32ef4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bigshow-32ef4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClSloBWsA8ATWDtGno0B_bhGaBbUR5Lcw',
    appId: '1:473743969289:android:d74dcce57739d08bae3cd8',
    messagingSenderId: '473743969289',
    projectId: 'bigshow-32ef4',
    databaseURL: 'https://bigshow-32ef4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bigshow-32ef4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5Fli7nloidRGgaybTCroFTqFW7Zugxw4',
    appId: '1:473743969289:ios:1b67add0ce6b87b2ae3cd8',
    messagingSenderId: '473743969289',
    projectId: 'bigshow-32ef4',
    databaseURL: 'https://bigshow-32ef4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bigshow-32ef4.appspot.com',
    iosBundleId: 'com.example.bigshow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5Fli7nloidRGgaybTCroFTqFW7Zugxw4',
    appId: '1:473743969289:ios:a0184ce390d3ae3aae3cd8',
    messagingSenderId: '473743969289',
    projectId: 'bigshow-32ef4',
    databaseURL: 'https://bigshow-32ef4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bigshow-32ef4.appspot.com',
    iosBundleId: 'com.example.bigshow.RunnerTests',
  );
}
